### ISSUE TITLE
lower() and upper() do not work on UTF-8 strings (Lua 5.1, Lua5.3)

### ISSUE THREAD

**Issue by shmuz** [Stepets/utf8.lua#7]
The file `test.lua` contains the following text encoded in UTF-8:
```Lua
local u = (require "stepets.utf8"):init()
assert(u.lower("АБВ") == "абв")
assert(u.upper("абв") == "АБВ")
```
This test fails.

**Comment by Stepets** [comment]
Thanks for reporting this!
I'm not sure how to solve this. I intentionally didn't put any tolower/toupper tests because this functions work for unicode only when ffi available.

Possible solution I don't like personally is to generate huge map containing all codepoint metadata. Ship it within library and use when ffi is not available

**Comment by shmuz** [comment]
> this functions work for unicode only when ffi available.

But if I run it with LuaJIT 2.1 (which has FFI) it also fails.

**Comment by Stepets** [comment]
Can you run this configuration? 
```Lua
local u = require('stepets.utf8')
u.config = {
  primitives = "primitives.native"
}
u:init()

assert(u.lower("АБВ") == "абв")
assert(u.upper("абв") == "АБВ")
```

**Comment by shmuz** [comment]
`luajit.exe: test3.lua:7: assertion failed!`

**Comment by Stepets** [comment]
Probably it's related to windows locales. Can you additionally configure `locale = "english_us.65001"`?

**Comment by shmuz** [comment]
BTW, I do not expect the problems that I report to be quickly fixed.
I'm not in search for an UTF-8 library, all my tests are pure curiosity.
But if they may help to improve an open source project, why not to report?

> Can you additionally configure locale = "english_us.65001"?

Maybe later (I've just received a task to do on my work).

**Comment by Stepets** [comment]
Fixed

https://github.com/Stepets/utf8.lua/blob/26d80da77e9363111333ff54a45c7b86ac808ca2/test/test.lua#L28-L31

**Comment by shmuz** [comment]
I've just downloaded it, and both assertions still fail with LuaJIT 2.1 on Windows.

**Comment by Stepets** [comment]
LuaJIT 2.1 build with MSVC works
LuaJIT 2.1 build with MinGW doesn't work
LuaJIT 2.1 build with MinGW (make CFLAGS=-D_UNICODE=1) works

**Comment by Stepets** [comment]
Test with LuaJIT 2.1 build with MSVC works
Test with LuaJIT 2.1 build with MinGW doesn't work

I'm not expirienced enough with windows to get MinGW build working.
My guess is: LuaJIT/MinGW cannot link to native towlower/towupper functions.
Thought building LuaJIT with [_UNICODE](https://sourceforge.net/p/mingw-w64/wiki2/Unicode%20apps/) defined will fix this. But it doesn't.
`/c/MinGW/bin/mingw32-make.exe CFLAGS=-D_UNICODE=1`

**Comment by shmuz** [comment]
I can confirm that with MSVC build of LuaJIT it works (just tested). OK.
